services:
  database:
    image: 'postgres:16.1-alpine'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=dddlecture'
      - 'POSTGRES_DB=dddlecture'
      - 'POSTGRES_PASSWORD=secret'